#Avaible: [english, french, korean, spanish, polish]
language: 'english'
winMessage: "&aYou Won in &e %attempt &aattempts" # %attempt
loseMessage: "&aYou lost"
wrongWord: "&cWrong word"
scoreboardTitle: "&aWordle"
playedToday: "&cYou have already played today"
startGame: "&aGame started, type '/wordle' again to pause game"
pauseGame: "&aGame paused"
cancelWord: "&cYou can't use this word in chat"
giveReward: true
reward:
  ITEM:
    material: iron_ingot
    ammount: 2
  COMMAND:
    command: gamemode creative %player
